// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu.proto

package com.olivia.proto;

public final class Computer {
  private Computer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cpu_Cpu_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cpu_Cpu_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cpu_Cpu_Frequency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cpu_Cpu_Frequency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cpu_Cpu_Cache_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cpu_Cpu_Cache_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cpu_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cpu_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcpu.proto\022\003cpu\"\216\002\n\003Cpu\022\r\n\005brand\030\001 \001(\t\022" +
      "\r\n\005cache\030\002 \001(\005\022!\n\tfrequency\030\003 \001(\0132\016.cpu." +
      "Cpu.Cache\032y\n\tFrequency\022\016\n\006number\030\001 \001(\005\022)" +
      "\n\004unit\030\002 \001(\0162\033.cpu.Cpu.Frequency.ByteUni" +
      "t\"1\n\010ByteUnit\022\005\n\001B\020\000\022\006\n\002KB\020\001\022\006\n\002MB\020\002\022\006\n\002" +
      "GB\020\003\022\006\n\002TB\020\004\032K\n\005Cache\022\016\n\006number\030\001 \001(\005\"2\n" +
      "\rFrequencyUnit\022\006\n\002HZ\020\000\022\007\n\003KHZ\020\001\022\007\n\003MHZ\020\002" +
      "\022\007\n\003GHZ\020\003\"\007\n\005Empty2*\n\nCpuService\022\034\n\004Ping" +
      "\022\n.cpu.Empty\032\010.cpu.CpuB\036\n\020com.olivia.pro" +
      "toB\010ComputerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cpu_Cpu_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cpu_Cpu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cpu_Cpu_descriptor,
        new java.lang.String[] { "Brand", "Cache", "Frequency", });
    internal_static_cpu_Cpu_Frequency_descriptor =
      internal_static_cpu_Cpu_descriptor.getNestedTypes().get(0);
    internal_static_cpu_Cpu_Frequency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cpu_Cpu_Frequency_descriptor,
        new java.lang.String[] { "Number", "Unit", });
    internal_static_cpu_Cpu_Cache_descriptor =
      internal_static_cpu_Cpu_descriptor.getNestedTypes().get(1);
    internal_static_cpu_Cpu_Cache_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cpu_Cpu_Cache_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_cpu_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cpu_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cpu_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
