// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu.proto

package com.olivia.proto;

/**
 * Protobuf type {@code cpu.Cpu}
 */
public  final class Cpu extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cpu.Cpu)
    CpuOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Cpu.newBuilder() to construct.
  private Cpu(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Cpu() {
    brand_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Cpu();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Cpu(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            brand_ = s;
            break;
          }
          case 16: {

            cache_ = input.readInt32();
            break;
          }
          case 26: {
            com.olivia.proto.Cpu.Cache.Builder subBuilder = null;
            if (frequency_ != null) {
              subBuilder = frequency_.toBuilder();
            }
            frequency_ = input.readMessage(com.olivia.proto.Cpu.Cache.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(frequency_);
              frequency_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.olivia.proto.Computer.internal_static_cpu_Cpu_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.olivia.proto.Computer.internal_static_cpu_Cpu_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.olivia.proto.Cpu.class, com.olivia.proto.Cpu.Builder.class);
  }

  public interface FrequencyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cpu.Cpu.Frequency)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    int getNumber();

    /**
     * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    int getUnitValue();
    /**
     * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
     * @return The unit.
     */
    com.olivia.proto.Cpu.Frequency.ByteUnit getUnit();
  }
  /**
   * Protobuf type {@code cpu.Cpu.Frequency}
   */
  public  static final class Frequency extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cpu.Cpu.Frequency)
      FrequencyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Frequency.newBuilder() to construct.
    private Frequency(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Frequency() {
      unit_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Frequency();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Frequency(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              number_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              unit_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_Frequency_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_Frequency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.olivia.proto.Cpu.Frequency.class, com.olivia.proto.Cpu.Frequency.Builder.class);
    }

    /**
     * Protobuf enum {@code cpu.Cpu.Frequency.ByteUnit}
     */
    public enum ByteUnit
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>B = 0;</code>
       */
      B(0),
      /**
       * <code>KB = 1;</code>
       */
      KB(1),
      /**
       * <code>MB = 2;</code>
       */
      MB(2),
      /**
       * <code>GB = 3;</code>
       */
      GB(3),
      /**
       * <code>TB = 4;</code>
       */
      TB(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>B = 0;</code>
       */
      public static final int B_VALUE = 0;
      /**
       * <code>KB = 1;</code>
       */
      public static final int KB_VALUE = 1;
      /**
       * <code>MB = 2;</code>
       */
      public static final int MB_VALUE = 2;
      /**
       * <code>GB = 3;</code>
       */
      public static final int GB_VALUE = 3;
      /**
       * <code>TB = 4;</code>
       */
      public static final int TB_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ByteUnit valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ByteUnit forNumber(int value) {
        switch (value) {
          case 0: return B;
          case 1: return KB;
          case 2: return MB;
          case 3: return GB;
          case 4: return TB;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ByteUnit>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ByteUnit> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ByteUnit>() {
              public ByteUnit findValueByNumber(int number) {
                return ByteUnit.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.olivia.proto.Cpu.Frequency.getDescriptor().getEnumTypes().get(0);
      }

      private static final ByteUnit[] VALUES = values();

      public static ByteUnit valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ByteUnit(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cpu.Cpu.Frequency.ByteUnit)
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    public int getNumber() {
      return number_;
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    private int unit_;
    /**
     * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
     * @return The unit.
     */
    public com.olivia.proto.Cpu.Frequency.ByteUnit getUnit() {
      @SuppressWarnings("deprecation")
      com.olivia.proto.Cpu.Frequency.ByteUnit result = com.olivia.proto.Cpu.Frequency.ByteUnit.valueOf(unit_);
      return result == null ? com.olivia.proto.Cpu.Frequency.ByteUnit.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (number_ != 0) {
        output.writeInt32(1, number_);
      }
      if (unit_ != com.olivia.proto.Cpu.Frequency.ByteUnit.B.getNumber()) {
        output.writeEnum(2, unit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      if (unit_ != com.olivia.proto.Cpu.Frequency.ByteUnit.B.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, unit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.olivia.proto.Cpu.Frequency)) {
        return super.equals(obj);
      }
      com.olivia.proto.Cpu.Frequency other = (com.olivia.proto.Cpu.Frequency) obj;

      if (getNumber()
          != other.getNumber()) return false;
      if (unit_ != other.unit_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + unit_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.olivia.proto.Cpu.Frequency parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Frequency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.olivia.proto.Cpu.Frequency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.olivia.proto.Cpu.Frequency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.olivia.proto.Cpu.Frequency prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cpu.Cpu.Frequency}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cpu.Cpu.Frequency)
        com.olivia.proto.Cpu.FrequencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.olivia.proto.Computer.internal_static_cpu_Cpu_Frequency_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.olivia.proto.Computer.internal_static_cpu_Cpu_Frequency_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.olivia.proto.Cpu.Frequency.class, com.olivia.proto.Cpu.Frequency.Builder.class);
      }

      // Construct using com.olivia.proto.Cpu.Frequency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = 0;

        unit_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.olivia.proto.Computer.internal_static_cpu_Cpu_Frequency_descriptor;
      }

      @java.lang.Override
      public com.olivia.proto.Cpu.Frequency getDefaultInstanceForType() {
        return com.olivia.proto.Cpu.Frequency.getDefaultInstance();
      }

      @java.lang.Override
      public com.olivia.proto.Cpu.Frequency build() {
        com.olivia.proto.Cpu.Frequency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.olivia.proto.Cpu.Frequency buildPartial() {
        com.olivia.proto.Cpu.Frequency result = new com.olivia.proto.Cpu.Frequency(this);
        result.number_ = number_;
        result.unit_ = unit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.olivia.proto.Cpu.Frequency) {
          return mergeFrom((com.olivia.proto.Cpu.Frequency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.olivia.proto.Cpu.Frequency other) {
        if (other == com.olivia.proto.Cpu.Frequency.getDefaultInstance()) return this;
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        if (other.unit_ != 0) {
          setUnitValue(other.getUnitValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.olivia.proto.Cpu.Frequency parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.olivia.proto.Cpu.Frequency) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 1;</code>
       * @return The number.
       */
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }

      private int unit_ = 0;
      /**
       * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
       * @return The enum numeric value on the wire for unit.
       */
      public int getUnitValue() {
        return unit_;
      }
      /**
       * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
       * @param value The enum numeric value on the wire for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitValue(int value) {
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
       * @return The unit.
       */
      public com.olivia.proto.Cpu.Frequency.ByteUnit getUnit() {
        @SuppressWarnings("deprecation")
        com.olivia.proto.Cpu.Frequency.ByteUnit result = com.olivia.proto.Cpu.Frequency.ByteUnit.valueOf(unit_);
        return result == null ? com.olivia.proto.Cpu.Frequency.ByteUnit.UNRECOGNIZED : result;
      }
      /**
       * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(com.olivia.proto.Cpu.Frequency.ByteUnit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cpu.Cpu.Frequency.ByteUnit unit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        
        unit_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cpu.Cpu.Frequency)
    }

    // @@protoc_insertion_point(class_scope:cpu.Cpu.Frequency)
    private static final com.olivia.proto.Cpu.Frequency DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.olivia.proto.Cpu.Frequency();
    }

    public static com.olivia.proto.Cpu.Frequency getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Frequency>
        PARSER = new com.google.protobuf.AbstractParser<Frequency>() {
      @java.lang.Override
      public Frequency parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frequency(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Frequency> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Frequency> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.olivia.proto.Cpu.Frequency getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CacheOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cpu.Cpu.Cache)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    int getNumber();
  }
  /**
   * Protobuf type {@code cpu.Cpu.Cache}
   */
  public  static final class Cache extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cpu.Cpu.Cache)
      CacheOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cache.newBuilder() to construct.
    private Cache(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cache() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cache();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cache(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              number_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_Cache_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_Cache_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.olivia.proto.Cpu.Cache.class, com.olivia.proto.Cpu.Cache.Builder.class);
    }

    /**
     * Protobuf enum {@code cpu.Cpu.Cache.FrequencyUnit}
     */
    public enum FrequencyUnit
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HZ = 0;</code>
       */
      HZ(0),
      /**
       * <code>KHZ = 1;</code>
       */
      KHZ(1),
      /**
       * <code>MHZ = 2;</code>
       */
      MHZ(2),
      /**
       * <code>GHZ = 3;</code>
       */
      GHZ(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>HZ = 0;</code>
       */
      public static final int HZ_VALUE = 0;
      /**
       * <code>KHZ = 1;</code>
       */
      public static final int KHZ_VALUE = 1;
      /**
       * <code>MHZ = 2;</code>
       */
      public static final int MHZ_VALUE = 2;
      /**
       * <code>GHZ = 3;</code>
       */
      public static final int GHZ_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FrequencyUnit valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static FrequencyUnit forNumber(int value) {
        switch (value) {
          case 0: return HZ;
          case 1: return KHZ;
          case 2: return MHZ;
          case 3: return GHZ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FrequencyUnit>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FrequencyUnit> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FrequencyUnit>() {
              public FrequencyUnit findValueByNumber(int number) {
                return FrequencyUnit.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.olivia.proto.Cpu.Cache.getDescriptor().getEnumTypes().get(0);
      }

      private static final FrequencyUnit[] VALUES = values();

      public static FrequencyUnit valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FrequencyUnit(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cpu.Cpu.Cache.FrequencyUnit)
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>int32 number = 1;</code>
     * @return The number.
     */
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (number_ != 0) {
        output.writeInt32(1, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.olivia.proto.Cpu.Cache)) {
        return super.equals(obj);
      }
      com.olivia.proto.Cpu.Cache other = (com.olivia.proto.Cpu.Cache) obj;

      if (getNumber()
          != other.getNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.olivia.proto.Cpu.Cache parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Cache parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.olivia.proto.Cpu.Cache parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.olivia.proto.Cpu.Cache parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.olivia.proto.Cpu.Cache prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cpu.Cpu.Cache}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cpu.Cpu.Cache)
        com.olivia.proto.Cpu.CacheOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.olivia.proto.Computer.internal_static_cpu_Cpu_Cache_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.olivia.proto.Computer.internal_static_cpu_Cpu_Cache_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.olivia.proto.Cpu.Cache.class, com.olivia.proto.Cpu.Cache.Builder.class);
      }

      // Construct using com.olivia.proto.Cpu.Cache.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.olivia.proto.Computer.internal_static_cpu_Cpu_Cache_descriptor;
      }

      @java.lang.Override
      public com.olivia.proto.Cpu.Cache getDefaultInstanceForType() {
        return com.olivia.proto.Cpu.Cache.getDefaultInstance();
      }

      @java.lang.Override
      public com.olivia.proto.Cpu.Cache build() {
        com.olivia.proto.Cpu.Cache result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.olivia.proto.Cpu.Cache buildPartial() {
        com.olivia.proto.Cpu.Cache result = new com.olivia.proto.Cpu.Cache(this);
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.olivia.proto.Cpu.Cache) {
          return mergeFrom((com.olivia.proto.Cpu.Cache)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.olivia.proto.Cpu.Cache other) {
        if (other == com.olivia.proto.Cpu.Cache.getDefaultInstance()) return this;
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.olivia.proto.Cpu.Cache parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.olivia.proto.Cpu.Cache) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 1;</code>
       * @return The number.
       */
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cpu.Cpu.Cache)
    }

    // @@protoc_insertion_point(class_scope:cpu.Cpu.Cache)
    private static final com.olivia.proto.Cpu.Cache DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.olivia.proto.Cpu.Cache();
    }

    public static com.olivia.proto.Cpu.Cache getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cache>
        PARSER = new com.google.protobuf.AbstractParser<Cache>() {
      @java.lang.Override
      public Cache parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cache(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cache> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cache> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.olivia.proto.Cpu.Cache getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int BRAND_FIELD_NUMBER = 1;
  private volatile java.lang.Object brand_;
  /**
   * <pre>
   * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
   * </pre>
   *
   * <code>string brand = 1;</code>
   * @return The brand.
   */
  public java.lang.String getBrand() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brand_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
   * </pre>
   *
   * <code>string brand = 1;</code>
   * @return The bytes for brand.
   */
  public com.google.protobuf.ByteString
      getBrandBytes() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CACHE_FIELD_NUMBER = 2;
  private int cache_;
  /**
   * <code>int32 cache = 2;</code>
   * @return The cache.
   */
  public int getCache() {
    return cache_;
  }

  public static final int FREQUENCY_FIELD_NUMBER = 3;
  private com.olivia.proto.Cpu.Cache frequency_;
  /**
   * <code>.cpu.Cpu.Cache frequency = 3;</code>
   * @return Whether the frequency field is set.
   */
  public boolean hasFrequency() {
    return frequency_ != null;
  }
  /**
   * <code>.cpu.Cpu.Cache frequency = 3;</code>
   * @return The frequency.
   */
  public com.olivia.proto.Cpu.Cache getFrequency() {
    return frequency_ == null ? com.olivia.proto.Cpu.Cache.getDefaultInstance() : frequency_;
  }
  /**
   * <code>.cpu.Cpu.Cache frequency = 3;</code>
   */
  public com.olivia.proto.Cpu.CacheOrBuilder getFrequencyOrBuilder() {
    return getFrequency();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBrandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
    }
    if (cache_ != 0) {
      output.writeInt32(2, cache_);
    }
    if (frequency_ != null) {
      output.writeMessage(3, getFrequency());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBrandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
    }
    if (cache_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cache_);
    }
    if (frequency_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFrequency());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.olivia.proto.Cpu)) {
      return super.equals(obj);
    }
    com.olivia.proto.Cpu other = (com.olivia.proto.Cpu) obj;

    if (!getBrand()
        .equals(other.getBrand())) return false;
    if (getCache()
        != other.getCache()) return false;
    if (hasFrequency() != other.hasFrequency()) return false;
    if (hasFrequency()) {
      if (!getFrequency()
          .equals(other.getFrequency())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BRAND_FIELD_NUMBER;
    hash = (53 * hash) + getBrand().hashCode();
    hash = (37 * hash) + CACHE_FIELD_NUMBER;
    hash = (53 * hash) + getCache();
    if (hasFrequency()) {
      hash = (37 * hash) + FREQUENCY_FIELD_NUMBER;
      hash = (53 * hash) + getFrequency().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.olivia.proto.Cpu parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.olivia.proto.Cpu parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.olivia.proto.Cpu parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.olivia.proto.Cpu parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.olivia.proto.Cpu parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.olivia.proto.Cpu parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.olivia.proto.Cpu parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.olivia.proto.Cpu parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.olivia.proto.Cpu parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.olivia.proto.Cpu parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.olivia.proto.Cpu parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.olivia.proto.Cpu parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.olivia.proto.Cpu prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cpu.Cpu}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cpu.Cpu)
      com.olivia.proto.CpuOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.olivia.proto.Cpu.class, com.olivia.proto.Cpu.Builder.class);
    }

    // Construct using com.olivia.proto.Cpu.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      brand_ = "";

      cache_ = 0;

      if (frequencyBuilder_ == null) {
        frequency_ = null;
      } else {
        frequency_ = null;
        frequencyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.olivia.proto.Computer.internal_static_cpu_Cpu_descriptor;
    }

    @java.lang.Override
    public com.olivia.proto.Cpu getDefaultInstanceForType() {
      return com.olivia.proto.Cpu.getDefaultInstance();
    }

    @java.lang.Override
    public com.olivia.proto.Cpu build() {
      com.olivia.proto.Cpu result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.olivia.proto.Cpu buildPartial() {
      com.olivia.proto.Cpu result = new com.olivia.proto.Cpu(this);
      result.brand_ = brand_;
      result.cache_ = cache_;
      if (frequencyBuilder_ == null) {
        result.frequency_ = frequency_;
      } else {
        result.frequency_ = frequencyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.olivia.proto.Cpu) {
        return mergeFrom((com.olivia.proto.Cpu)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.olivia.proto.Cpu other) {
      if (other == com.olivia.proto.Cpu.getDefaultInstance()) return this;
      if (!other.getBrand().isEmpty()) {
        brand_ = other.brand_;
        onChanged();
      }
      if (other.getCache() != 0) {
        setCache(other.getCache());
      }
      if (other.hasFrequency()) {
        mergeFrequency(other.getFrequency());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.olivia.proto.Cpu parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.olivia.proto.Cpu) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object brand_ = "";
    /**
     * <pre>
     * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
     * </pre>
     *
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
     * </pre>
     *
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
     * </pre>
     *
     * <code>string brand = 1;</code>
     * @param value The brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
     * </pre>
     *
     * <code>string brand = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
     * </pre>
     *
     * <code>string brand = 1;</code>
     * @param value The bytes for brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value;
      onChanged();
      return this;
    }

    private int cache_ ;
    /**
     * <code>int32 cache = 2;</code>
     * @return The cache.
     */
    public int getCache() {
      return cache_;
    }
    /**
     * <code>int32 cache = 2;</code>
     * @param value The cache to set.
     * @return This builder for chaining.
     */
    public Builder setCache(int value) {
      
      cache_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cache = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCache() {
      
      cache_ = 0;
      onChanged();
      return this;
    }

    private com.olivia.proto.Cpu.Cache frequency_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.olivia.proto.Cpu.Cache, com.olivia.proto.Cpu.Cache.Builder, com.olivia.proto.Cpu.CacheOrBuilder> frequencyBuilder_;
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     * @return Whether the frequency field is set.
     */
    public boolean hasFrequency() {
      return frequencyBuilder_ != null || frequency_ != null;
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     * @return The frequency.
     */
    public com.olivia.proto.Cpu.Cache getFrequency() {
      if (frequencyBuilder_ == null) {
        return frequency_ == null ? com.olivia.proto.Cpu.Cache.getDefaultInstance() : frequency_;
      } else {
        return frequencyBuilder_.getMessage();
      }
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    public Builder setFrequency(com.olivia.proto.Cpu.Cache value) {
      if (frequencyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frequency_ = value;
        onChanged();
      } else {
        frequencyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    public Builder setFrequency(
        com.olivia.proto.Cpu.Cache.Builder builderForValue) {
      if (frequencyBuilder_ == null) {
        frequency_ = builderForValue.build();
        onChanged();
      } else {
        frequencyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    public Builder mergeFrequency(com.olivia.proto.Cpu.Cache value) {
      if (frequencyBuilder_ == null) {
        if (frequency_ != null) {
          frequency_ =
            com.olivia.proto.Cpu.Cache.newBuilder(frequency_).mergeFrom(value).buildPartial();
        } else {
          frequency_ = value;
        }
        onChanged();
      } else {
        frequencyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    public Builder clearFrequency() {
      if (frequencyBuilder_ == null) {
        frequency_ = null;
        onChanged();
      } else {
        frequency_ = null;
        frequencyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    public com.olivia.proto.Cpu.Cache.Builder getFrequencyBuilder() {
      
      onChanged();
      return getFrequencyFieldBuilder().getBuilder();
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    public com.olivia.proto.Cpu.CacheOrBuilder getFrequencyOrBuilder() {
      if (frequencyBuilder_ != null) {
        return frequencyBuilder_.getMessageOrBuilder();
      } else {
        return frequency_ == null ?
            com.olivia.proto.Cpu.Cache.getDefaultInstance() : frequency_;
      }
    }
    /**
     * <code>.cpu.Cpu.Cache frequency = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.olivia.proto.Cpu.Cache, com.olivia.proto.Cpu.Cache.Builder, com.olivia.proto.Cpu.CacheOrBuilder> 
        getFrequencyFieldBuilder() {
      if (frequencyBuilder_ == null) {
        frequencyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.olivia.proto.Cpu.Cache, com.olivia.proto.Cpu.Cache.Builder, com.olivia.proto.Cpu.CacheOrBuilder>(
                getFrequency(),
                getParentForChildren(),
                isClean());
        frequency_ = null;
      }
      return frequencyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cpu.Cpu)
  }

  // @@protoc_insertion_point(class_scope:cpu.Cpu)
  private static final com.olivia.proto.Cpu DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.olivia.proto.Cpu();
  }

  public static com.olivia.proto.Cpu getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Cpu>
      PARSER = new com.google.protobuf.AbstractParser<Cpu>() {
    @java.lang.Override
    public Cpu parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Cpu(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Cpu> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Cpu> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.olivia.proto.Cpu getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

