// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu.proto

package com.olivia.proto;

public interface CpuOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cpu.Cpu)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
   * </pre>
   *
   * <code>string brand = 1;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <pre>
   * Intel(R) Core(TM) i7-4770HQ CPU &#64; 2.20GHz
   * </pre>
   *
   * <code>string brand = 1;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>int32 cache = 2;</code>
   * @return The cache.
   */
  int getCache();

  /**
   * <code>.cpu.Cpu.Cache frequency = 3;</code>
   * @return Whether the frequency field is set.
   */
  boolean hasFrequency();
  /**
   * <code>.cpu.Cpu.Cache frequency = 3;</code>
   * @return The frequency.
   */
  com.olivia.proto.Cpu.Cache getFrequency();
  /**
   * <code>.cpu.Cpu.Cache frequency = 3;</code>
   */
  com.olivia.proto.Cpu.CacheOrBuilder getFrequencyOrBuilder();
}
