// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu.proto

package com.olivia.proto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cpu.Empty)
    com.google.protobuf.MessageOrBuilder {
}
